#!/usr/bin/env bash

source cecho.sh
source install.sh

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    install_linux
elif [[ "$OSTYPE" == "darwin"* ]]; then
    install_mac
else
    echo "Unsupported OS"
fi

