#! /bin/bash

echo "get submodules"
git submodule init
git pull --recurse-submodules

echo "install prereqs"
sudo apt install stow
sudo apt install fish

echo "stow git"
stow git
echo "stow vim"
stow vim
echo "stow fish"
stow fish
