#! /bin/sh

xmodmap -e "remove mod1 = Alt_L"
xmodmap -e "add mod4 = Alt_L"

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
